# Generated by Django 3.1 on 2020-08-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies_app', '0002_auto_20200829_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='active',
            field=models.BooleanField(),
        ),
    ]
