# Generated by Django 3.1 on 2020-08-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies_app', '0003_auto_20200829_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('friendship', models.CharField(max_length=20)),
            ],
        ),
    ]
