# Generated by Django 3.1 on 2020-09-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies_app', '0004_friend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friendship',
            field=models.CharField(choices=[('Old', 'OLD FRIEND'), ('Close', 'CLOSE FRIEND'), ('Good', 'GOOD FRIEND'), ('New', 'NEW FRIEND')], default='Old', max_length=100),
        ),
    ]
