# Generated by Django 3.1 on 2020-09-05 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies_app', '0007_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='activities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hobbies_app.activity'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='friends',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='hobbies_app.friend'),
        ),
    ]
