# Generated by Django 3.1 on 2020-09-05 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies_app', '0008_auto_20200905_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='activities',
        ),
        migrations.AddField(
            model_name='hobby',
            name='activities',
            field=models.ManyToManyField(to='hobbies_app.Activity'),
        ),
        migrations.AlterField(
            model_name='hobby',
            name='friends',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hobbies_app.friend'),
        ),
    ]
