# Generated by Django 3.1 on 2020-09-06 01:31

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies_app', '0009_auto_20200905_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='people',
            field=models.CharField(default={django.contrib.auth.models.User}, max_length=100),
        ),
    ]
