# Generated by Django 3.1 on 2020-09-06 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hobbies_app', '0010_activity_people'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cat',
            new_name='hobby',
        ),
    ]
